# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3fb7ab2f4fc26b2dea272daa01b96113b0205232177fe97084ff5f14080e2ed7a7282516956cb951abca8a1674e45f4efd3eddc0fdfcdf8943e8fd2bfda1e42

test:
  secret_key_base: 3f24ce1578962e48cd9cf1c215068a52b2d3f322249030afcbb66d72833dec197d2de20fc701541b5486310d4fd8a24e4564da7943137bd474a9c9769f4087ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
